# Generated by Django 5.0.6 on 2024-11-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_resume_alter_contactinfo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='user_directory_path'),
        ),
    ]
