# Generated by Django 5.0.6 on 2024-09-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=300)),
                ('skil', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Experience',
            },
        ),
    ]
