# Generated by Django 5.0.6 on 2024-09-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_education_name_alter_education_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_number', models.CharField(blank=True, max_length=14, null=True)),
                ('Massage', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contactinfos',
            },
        ),
    ]
